### ISSUE TITLE
Nickname in TabList resets when afk-status is enabled

### ISSUE THREAD

**Issue by Adam759** [montlikadani/TabList#107]
### Describe your problem to what is
I have been going in circles for quite some time now. I am having an issue with Nickname and afk-status. I am using EssentialsX to manage nicknames. It works completely fine with `use-essentials-nickname: true` and with tabname enabled in Tablist config. However, when I enable afk-status, it does append the default [AFK] to the end of the tabname, but it resets the name in the tablist to the original name before the nickname. It then stays like this until rejoin. Sometimes, after this sequence, a WARN is spammed in console too until the server is reset. See screenshots for it.

I have checked over my other plugins to ensure they would not be interfering with the tablist, especially on an AFK event. I am using VentureChat for my chat system and have all tab modifying settings disabled on it, I even disabled it and it still happens. I made sure all tab modifying settings were disabled in EssentialsX as well. I have attached a screenshot of all my other plugins at the very end as well, of which I couldn't find any interference either. 

### Details
Plugin version: 4.8
Software (Spigot/Bukkit etc.. `/version`) version: Paper Spigot 1.14.4 Build 221

Running on Linux Ubuntu Server 18.04 - Java 11

### Console error
Hundreds of these:
```
[03:41:38 WARN]: [TabList] Plugin TabList v4.8 generated an exception while executing task 4556
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Long.parseLong(Long.java:702) ~[?:?]
        at java.lang.Long.parseLong(Long.java:817) ~[?:?]
        at java.text.DigitList.getLong(DigitList.java:195) ~[?:?]
        at java.text.DecimalFormat.parse(DecimalFormat.java:2123) ~[?:?]
        at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2240) ~[?:?]
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1541) ~[?:?]
        at java.text.DateFormat.parse(DateFormat.java:393) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.format12(PlayerUtil.java:59) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:297) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:375) ~[?:?]
        at hu.montlikadani.tablist.TabList.setPlaceholders(TabList.java:1345) ~[?:?]
        at hu.montlikadani.tablist.Variables.replaceVariables(Variables.java:100) ~[?:?]
        at hu.montlikadani.tablist.TabList.sendTab(TabList.java:1022) ~[?:?]
        at hu.montlikadani.tablist.TabList.lambda$8(TabList.java:708) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-221]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

[03:41:53 WARN]: [TabList] Plugin TabList v4.8 generated an exception while executing task 4554
java.lang.NumberFormatException: multiple points
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:543) ~[?:?]
        at java.text.DigitList.getDouble(DigitList.java:169) ~[?:?]
        at java.text.DecimalFormat.parse(DecimalFormat.java:2128) ~[?:?]
        at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2240) ~[?:?]
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1541) ~[?:?]
        at java.text.DateFormat.parse(DateFormat.java:393) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.format12(PlayerUtil.java:59) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:297) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:375) ~[?:?]
        at hu.montlikadani.tablist.TabList.setPlaceholders(TabList.java:1345) ~[?:?]
        at hu.montlikadani.tablist.Variables.replaceVariables(Variables.java:100) ~[?:?]
        at hu.montlikadani.tablist.TabList.sendTab(TabList.java:1022) ~[?:?]
        at hu.montlikadani.tablist.TabList.lambda$8(TabList.java:708) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-221]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Configuration file(s)

config.yml:
```
#=================================OOO====================================#
#                     TabList Configuration File                         #
#                  Author, created by: montlikadani                      #
#=================================OOO====================================#
# [Default configuration]                                                #
# https://github.com/montlikadani/TabList/blob/master/config.yml         #
#                                                                        #
# [Placeholders]                                                         #
# https://github.com/montlikadani/TabList/wiki/Placeholders              #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# https://minecraft.gamepedia.com/Formatting_codes                       #
# - If you find a bug, send here:                                        #
# https://github.com/montlikadani/TabList/issues                         #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/TabList/wiki/Symbols                   #
# - If the string is empty does not send the message.                    #
#=================================OOO====================================#

# PlaceholderAPI use for the plugin.
placeholderapi: true

# Hook plugins
hook:
  # Hooking to my RageMode plugin. (https://www.spigotmc.org/resources/69169/)
  # If true, will disable the tablist, groups and the tablist objects, while
  # running a game.
  RageMode: false

# Different playerlist in different world.
per-world-player-list: false

# Fake players that are on the tab.
enable-fake-players: false

# Ignoring vanished players in %online-players% placeholder.
# true - does not count the vanished players to placeholder.
# Requires Essentials or SuperVanish plugin!
ignore-vanished-players-in-online-players: false

# Hides player from tab when afk status.
# Requires Essentials plugin!
hide-player-from-tab-when-afk: false

# Placeholder formatting
placeholder-format:
  # When the player changes the afk status, changes the tablist name format.
  afk-status:
    enable: true

    # Should show the afk format in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    format-yes: "&7 [AFK]&r"
    format-no: ""

  time:
    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    time-zone: "GMT0"

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Used for %server-time% placeholder.
    time-format:
      format: "mm:HH"
    # Used for %date% placeholder.
    date-format:
      format: "dd/MM/yyyy"

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # Use color coding "&" for color.
    good-ping:
      color: "&a"
      amount: 200
    medium-ping:
      color: "&6"
      amount: 500
    bad-ping: "&c"

  # TPS color format for %tps% placeholder.
  tps:
    enable: true

    # Use color coding "&" for color.
    good-tps:
      color: "&a"
      amount: 18.0
    medium-tps:
      color: "&6"
      amount: 16.0
    bad-tps: "&c"

# Custom variables with unlimited variables.
# Use: <something>: "&6Message..."
custom-variables:
  <name>: "&5&o%player_name%"
  <lines>: "&5&m======================"

# Enables to change prefix & suffix in player tablist.
# WARNING! Overwrites the tabname function.
change-prefix-suffix-in-tablist:
  enable: false

  # Refresh interval in seconds, if using animation then counts in ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0 you will required to execute the /tl rl command, to reload the groups.
  refresh-interval: 30

  # Do you want to use animation in groups?
  # This creates a new task scheduler when this enabled.
  # If this true, then you need to change the refresh interval such as 4, because counting in ticks.
  # If this false, then back to seconds interval.
  enable-animation: false

  # Disable groups in the given worlds.
  disabled-worlds:
    # Use the list as white list or not?
    # If true - Using the white list option and all worlds should be given to the list
    # to show in the specified worlds.
    # If false (default) - Using the disabled list option and if a world is given in the list
    # the groups will be disabled in that world.
    use-as-whitelist: false
    list:
    #- myWorld

  # By enabling this, you will be able to specify the correct Vault group name in groups file
  # and if correct, then it will grant the group to player.
  use-vault-group-names: true

  # Hide player group in tablist when the player is vanished?
  # Required Essentials plugin!
  hide-group-when-player-vanished: false

  # Hide player group in tablist when the player is afk?
  # Required Essentials plugin!
  hide-group-when-player-afk: false

  # Use the essentials nickname instead of player original name?
  # true - Using this format: "prefix playerNickName suffix"
  # false - Using this format: "prefix playerOriginalName suffix"
  use-essentials-nickname: false

  # Use the player displayname instead of groups?
  # This supports the player "prefix playerName suffix" format like on chat.
  # If the player has no any format on chat then display the player name.
  use-displayname: false

  # Scoreboard changing types (if you experience some problems by changing group).
  # scoreboard - Maximum character is 16 (if use 1.13+ version max. 64) in prefix & suffix.
  # namer - Max. character is unlimited.
  changing-type: scoreboard

# Tablist objective types
# Shows your current health (with life indicator), shows your current ping or a custom placeholder
# that shows number.
tablist-object-type:
  enable: false

  # Types:
  # ping - ping of player
  # health - health of player
  # custom - custom value
  type: ping

  # Objective settings
  object-settings:
    # The ping side next to the player's name indicates the right side.
    ping:
      # Ping update time interval in seconds.
      update-interval: 3

      # Which worlds do not show up in ping (world names)?
      disabled-worlds:
      #- testingWorld

    # The player health (life) the player's name indicates the right side.
    health:
      # Which worlds do not show the players health in tab?
      disabled-worlds:
      - world_the_end

      # Blacklisted players who do not show the health in tab.
      blacklisted-players:
      - exampleplayer
      - players

    # It only accepts number-ending placeholders, such as player levels (doubled numbers "2.1" do NOT work).
    custom:
      custom-value: "%player_level%"

      # Refresh interval in seconds.
      refresh-interval: 3

      # Which worlds do not show the custom value setting (world names)?
      disabled-worlds:
      #- worlds

# Changing player tablist name with unlimited characters.
tabname:
  # Allow to change player tab name.
  enable: true

  # Use the Essentials nickname instead of tab name?
  use-essentials-nickname: true

  # How many letters should be allowed?
  max-name-length: 200

  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false

  # Enables color coding for tab names. ("&")
  # false - disables all placeholders, symbols, and color codes.
  enable-color-code: true

  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: "&6"

  # Which worlds can not be change the tab name?
  disabled-worlds:
  #- myworld

  # Which names can not be used?
  blacklist-names:
  - tabname

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Plugin enable/disable messages in console.
# Use %newline% placeholder.
plugin-enable: '&6&l[&5&lTab&c&lList&6&l]&7&l >&a The plugin successfully enabled&6 v4.8&a!'
plugin-disable: '&6&l[&5&lTab&c&lList&6&l]&7&l >&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 14

```
tablist.yml:
```
# Tablist, header & footer with animation.

# Current plugin placeholders: https://github.com/montlikadani/TabList/wiki/Placeholders
# Use placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols

# Use %anim:animationName% placeholder to make an animation.

# How do I use this tab section? Usage: https://github.com/montlikadani/TabList/wiki/TabList-Usage

# Enable the tab? (Header & footer)
enabled: true

# Hide tab when the player is vanished?
# Required Essentials plugin!
hide-tab-when-player-vanished: false

# What world does not display the tab?
disabled-worlds:
- "world1"
- "worldTest"

# Blacklisted players, where the player not see the tab.
blacklisted-players:
#- myname

# Tab update time interval. (In ticks!)
# Set 0 to disable the tab refresh.
interval: 7

header:
- "&a&nBowlingotter Minecraft Server"
- "&7-   -   -"
- "&7Players Online: &a&o%server_online%&7&o/&2&o%server_max_players%"
- "&7All Time: &b&o%server_unique_joins%"
- "&7==================="
footer:
- "&7==================="
- "&bWelcome %essentials_nickname%"
- "&7Ping: &a%ping%"
- "&7TPS: &b%server_tps%"
- "&7-"
- "&c%player_world_time_12%"
- "&7-"
- "&7X:&a&o%player_x%&7 Y:&a&o%player_y%&7 Z:&a&o%player_z%"
- "&7-"
- "&6Current World: &c%player_world%"
# Per world tablist
per-world:
  # (Optional)
  # If the world name is not given, will see the default tab.
  #use-default-tab-if-world-not-given: true

  my_nether:
    header: "&3This is a per world plugin %anim:tablist%&3."
    footer: "&6World:&7 %player_world%"
  justWorld:
    header: "%anim:perWorld%"
    footer: "&6World:&7 %player_world%"

    # Per player in per world tablist
    per-player:
      # (Optional)
      # If the player name is not given, will see the default tab.
      #use-default-tab-if-player-not-given: true

      playerName:
        header: "&3This is a per player plugin %anim:tablist%&3."
        footer:
        - "&6World:&7 %player_world%"
        - "&aPlayer:&8 %player_name%"
  testWorld:
    # Per group in per world tablist
    # Requires Vault plugin!
    per-group:
      # (Optional)
      # If the group name is not given, will see the default tab.
      #use-default-tab-if-group-not-given: true

      groupName:
        header: "&3This is a per group plugin %anim:tablist%&3."
        footer:
        - "&6World:&7 %player_world%"
        - "&aGroup:&8 %vault_rank%"

# Per player tablist
per-player:
  # (Optional)
  # If the player name is not given, will see the default tab.
  #use-default-tab-if-player-not-given: false

  testplayer:
    header: "%anim:perPlayer%"
    footer: "<lines>"

# Per group tablist
# Requires Vault plugin!
per-group:
  # (Optional)
  # If the group name is not given, will see the default tab.
  #use-default-tab-if-group-not-given: true

  vaultGroup:
    header: "%anim:perGroupHead%"
    footer: "%anim:perGroupFoot%"
```

### Screenshots (optional)

Normal Tab Screen:
![image](https://user-images.githubusercontent.com/15002550/67372795-15924700-f544-11e9-8b8b-665c2ef1d99e.png)

After AFK timeout or when /eafk is used:
![image](https://user-images.githubusercontent.com/15002550/67372864-35c20600-f544-11e9-9d4d-f051d573207c.png)

After moving to escape AFK:
![image](https://user-images.githubusercontent.com/15002550/67372913-496d6c80-f544-11e9-8b9a-42105e37408d.png)

WARN Error spammed:
![image](https://user-images.githubusercontent.com/15002550/67374305-96ead900-f546-11e9-879e-fa68101b7cfc.png)

Sometimes `input string: ""` Will actually have something in between the "", usually numbers and letters, etc. Or, it will say "multiple points":
![image](https://user-images.githubusercontent.com/15002550/67374605-05c83200-f547-11e9-85be-b6eda5fb163a.png)

These all have the same body it would seem. Hundreds of these show up in a matter of seconds. 

All Plugins:
![image](https://user-images.githubusercontent.com/15002550/67374330-a10cd780-f546-11e9-800c-a6ba7d4d422a.png)
