### ISSUE TITLE
No staff prefix

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#14]
Spigot 1.12.2
TabList 2.4.3

With default _group.yml_ and _tablist.staff_ permission (via _LuckPerms_), I do not see the staff prefix in the tablist. Probably I am doing something wrong, but I don't see the problem.

**Comment by montlikadani** [comment]
There may be several bugs.
The first is that I have given two of the same permissions.
The other is that I've been working for a while.

**Comment by montlikadani** [comment]
@SlimeDog 
The _LuckPerms_ and the TabList plugin reloaded? Because, when you have given the permission, you must first reload the permission plugin and then the TabList plugin.

**Comment by SlimeDog** [comment]
Done. No joy.

Server restarted. No joy.

config.yml, empty lines and comments elided:
```
placeholderapi: true
per-world-player-list: false
remove-npc-name-from-tab: false
time-format: 'yyyy-MM-dd HH:mm:ss'
custom-variables:
  <name>: '&r%player_name%'
  <pluginauthor>: '&amontlikadani'
  <rightarrow>: '-->'
change-prefix-suffix-in-tablist: true
groups-refresh-interval: 200
ping-tab:
  enable: false
  interval: 3
  disabled-worlds: []
tabname:
  enable: false
  max-name-length: 200
  clear-player-tabname-on-quit: false
  enable-color-code: true
  default-color:
    enable: false
    color: '&6'
  disabled-worlds: []
  blacklist-names:
  - tabname
  enable-other-changed-name-message: false
  other-changed-name-message: '&3Your name is changed to&r %name%&3 by&e %sender%&3.'
health-tab:
  enable: false
  disabled-worlds: []
tablist:
  enable: true
  disabled-worlds: []
  interval: 4
  header:
    - '&7server: %player_server%\n&7world: %multiverse_world_alias%\n&7loc: %player_x% %player_y% %player_z%\n&7hydration: %thirst_level%/100\n&7faction: %factions_faction% %factions_onlinemembers%/%factions_allmembers%\n&7point$: %vault_eco_balance%\n&7==================='
  footer:
    - ''
enabled: true
metrics: false
check-update: false
logconsole: true
log-to-file: false
plugin-enable-message: true
plugin-enable: '%prefix% The plugin successfully enabled v2.4.3!'
plugin-disable-message: true
plugin-disable: '%prefix% The plugin successfully disabled!'
default-can-see-plugin-information: false
unknown-command-enable: true
unknown-command: '%prefix% Unknown command. Type "/%command% help" for help.'
```

**Comment by montlikadani** [comment]
@SlimeDog 
Is the group set for you which uses the permission?
I tested the PermissionsEx and the GroupManager plugin, it worked fine.

**Comment by montlikadani** [comment]
@SlimeDog 
Try: https://github.com/montlikadani/TabList/releases/tag/v2.4.3

**Comment by SlimeDog** [comment]
> Is the group set for you which uses the permission?

Yes. As mentioned ^^^ I am testing TabList 2.4.3 with LuckPerms.
```
>lp user <PLAYER_NAME_MASKED> permission checkinherits tablist.staff
[13:36:13 INFO]: [LP] <PLAYER_NAME_MASKED> has permission tablist.staff set to true in context global. (inherited from admin)
```
Server has been restarted. But the tablist contains only
- player head
- player name
- player ping

Given the group.yml content
```
groups:
  staff:
    prefix: '&a[&cStaff&a]&6 '
    suffix: ''
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: 'tablist.staff'
```
it should be
- player head
- &a[&cStaff&a]&6
- player name
- player ping

**Comment by montlikadani** [comment]
@SlimeDog
Update to the latest version: https://github.com/montlikadani/TabList/releases/tag/v2.4.3
Minor changes in groups.yml file:
groups:
  '1':
    prefix: ''
    suffix: "
    permission: tablist.staff

**Comment by SlimeDog** [comment]
Are you saying that there are two versions 2.4.3? Please increment version numbers for new releases, even dev releases. :(

**Comment by SlimeDog** [comment]
Note that the permission is misspelled once in the release description:  **tablist.onelinestaff**

**Comment by SlimeDog** [comment]
I made those changes. Still does not display _[Staff]_.

I don't think there is a problem with _LuckPerms_. Did you test with it?

**Comment by SlimeDog** [comment]
And tablist.onlinestaff is checked very 10 seconds.

**Comment by SlimeDog** [comment]
And presumably this should be:
```
groups:
  '1':
    prefix: '&a[&cStaff&a]&6 '
    suffix: ''
    permission: tablist.onlinestaff
```

**Comment by montlikadani** [comment]
@SlimeDog 
I do not usually change the new release (though that should be).
I had to change the permission because there is a 'Staff' group and if someone uses it then the permission will be confused.
I do not understand that groups work for me, but not for other users.

**Comment by montlikadani** [comment]
Did you remove groups from config.yml?

**Comment by montlikadani** [comment]
I've just tested the LuckPerms plugin and it works fine.

**Comment by SlimeDog** [comment]
OK. I'm going to re-install clean.

**Comment by montlikadani** [comment]
I'm update the plugin... Please wait.

**Comment by SlimeDog** [comment]
Spigot 1.12.2
TabList 2.4.4
LuckPerms 4.1.63

Prefixes are not displayed. I am in group admin, with permissions
```
- tablist.onlinestaff
- tablist.staff
- tablist.*
```
```
>lp user PLAYERNAME permission checkinherits tablist.onlinestaff
[07:50:17 INFO]: [LP] PLAYERNAME has permission tablist.onlinestaff set to true in context global. (inherited from admin)
>lp user PLAYERNAME permission checkinherits tablist.staff
[07:50:24 INFO]: [LP] PLAYERNAME has permission tablist.staff set to true in context global. (inherited from admin)
```
config.yml (comments and empty lines removed)
```
placeholderapi: true
per-world-player-list: false
remove-npc-name-from-tab: false
time-format: 'yyyy-MM-dd HH:mm:ss'
custom-variables:
  <name>: '&r%player_name%'
  <pluginauthor>: '&amontlikadani'
  <rightarrow>: '-->'
change-prefix-suffix-in-tablist: true
groups-refresh-interval: 200
ping-tab:
  enable: false
  interval: 3
  disabled-worlds: []
tabname:
  enable: false
  max-name-length: 200
  clear-player-tabname-on-quit: false
  enable-color-code: true
  default-color:
    enable: false
    color: '&6'
  disabled-worlds: []
  blacklist-names:
  - tabname
  enable-other-changed-name-message: false
  other-changed-name-message: '&3Your name is changed to&r %name%&3 by&e %sender%&3.'
health-tab:
  enable: false
  disabled-worlds: []
tablist:
  enable: true
  disabled-worlds:
  - lobby
  interval: 4
  header:
    - '&7server: %player_server%\n&7world: %multiverse_world_alias%\n&7loc: %player_x% %player_y% %player_z%\n&7hydration: %thirst_level%/100\n&7faction: %factions_faction% %factions_onlinemembers%/%factions_allmembers%\n&7point$: %vault_eco_balance%\n&7==================='
  footer:
    - ''
enabled: true
metrics: false
check-update: false
logconsole: true
log-to-file: false
plugin-enable-message: true
plugin-enable: '%prefix% The plugin successfully enabled v2.4.3!'
plugin-disable-message: true
plugin-disable: '%prefix% The plugin successfully disabled!'
default-can-see-plugin-information: false
unknown-command-enable: true
unknown-command: '%prefix% Unknown command. Type "/%command% help" for help.'
```
groups.yml
```
# Group prefixes and suffixes. (Requires a permission system.)
# WARNING! Max character is 16 in prefix and suffix!
# Unlimited group.
groups:
  '1':
    prefix: '&a[&cStaff&a]&6 '
    suffix: ''
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.staff
  '2':
    prefix: '&7'
    suffix: ''
    # This permission must be in the permission system (e.g. GroupManager).
    permission: tablist.default
```
