### ISSUE TITLE
Prefixes of users with multiple groups in LuckPerms do not display properly

### ISSUE THREAD

**Issue by MellenIO** [montlikadani/TabList#166]
### Problem
See the following image:
https://i.imgur.com/fmuErpn.png

The 2 users at the bottom (starting A and t respectively) are VIP users. They also have another group - regular - which is a time-gated rank (that has no prefix in LuckPerms, and is just there to store X player has played Y hours)
https://i.imgur.com/RKk6idk.png

I've set up my `TabList/groups.yml` file to contain entries for both VIP and regular like so:
```
groups:
  Default:
    prefix: ' &7[m]'
  Admin:
    prefix: ' &c[a] '
    suffix: ''
    sort-priority: 0
  mod:
    prefix: ' &2[s] '
    suffix: ''
  vip:
    prefix: ' &a[v] '
    suffix: ''
  regular:
    prefix: ''
    suffix: ''
    permission: do.not.use <-- just one of many things I've tried to get VIP to show
```

The **primary group** for these users is the VIP group; regular is only a secondary group.

I would therefore expect in the tablist to show a green [v] for these users, but as the screenshots illustrate this is not the case.

### Details
Plugin version: 

Software version: PaperMC build 134

Relevant plugins: TabList v5.4.3, LuckPerms v5.1.75

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

configuration file: 

https://pastebin.com/hnu02S8i
### Screenshots (optional)

See above.
