### ISSUE TITLE
Groups not showing in tablist

### ISSUE THREAD

**Issue by cb12438** [montlikadani/TabList#207]
### Problem
Groups are not showing  in tablist i have vault and EssentialsX so idk why it is not working

Plugin version: 
latest
Software version: 
paper latest version

Relevant plugins: 
essentialsX, vault, PlaceHolderAPI

configuration file: 
Groups.yml: https://pastebin.com/xUDxxLv5
tablist.yml: https://pastebin.com/bcFx9kwh
config.yml: https://pastebin.com/8PUHeHke

![Screenshot (127)](https://user-images.githubusercontent.com/55159369/104260109-a732f080-5437-11eb-9827-03d1c57e083a.png)

**Comment by montlikadani** [comment]
In config.yml you have:
```yml
# Enable changing of prefix & suffix in player list?
# This option generates the groups.yml file.
change-prefix-suffix-in-tablist:
  enable: false
```

Please read the [wiki](https://github.com/montlikadani/TabList/wiki/How-to-create-a-group)
