### ISSUE TITLE
Tablist gets shrunk after turning off and back on

### ISSUE THREAD

**Issue by nikawiwi** [montlikadani/TabList#215]
### Problem
I just downloaded tablist today, was working well, didn't edit anything in the config files. Then tested the "toggle" command, it worked, but when I toggled tablist back on, I didn't have any of the animations or half of the info (RAM, website, colors, etc) It just said Tablist at the top, and then had all the players.
I tried deleting the jar and config folder and reinstalling, and now even without toggling it only shows the limited info.
I've tested this on 2 computers, and tried toggling someone else's off and on, and the same thing happens. Didn't include config since it is all default.

Thanks
N

### Details
Plugin version: 
5.5.2 (most recent)

Software version: 
Paper 1.16.5. v498

Relevant plugins: 
EssentialsX
Vault
Luckperms
Super Vanish

### Console error
```
Insert here the console error if you have it or use paste server.
```

**Comment by montlikadani** [comment]
There is file generated on server stop called `toggledtablists.yml`. This holds the toggled tablists for each player who's switched off the tablist. Deleting this will result to show the tablist for those players. Please include a screenshot about the "shrunk" and tablist from game.

**Comment by nikawiwi** [comment]
Ok, thank you! I will try deleting that in the morning.
Here is a screenshot of the shrunktablist:
<img width="260" alt="Screen Shot 2021-02-28 at 4 12 14 AM" src="https://user-images.githubusercontent.com/77725428/109413410-40cc4800-797b-11eb-80b8-eef2de53d7c3.png">

**Comment by montlikadani** [comment]
Delete this section entirely from tablist.yml:

```yml
permissions:
  '1':
    header:
    - "%anim:tablist%"
    - ""
    - "&7<57> &2%player%"
  node2:
    header: "%anim:tablist%"
    footer:
    - "&c+++++++++++++++"
    - "&a%player%, &e%world%"
    - "&c+++++++++++++++"
```
