### ISSUE TITLE
Meta formatting codes in groups doesn't work

### ISSUE THREAD

**Issue by Katrix** [montlikadani/TabList#216]
### Problem
Updating from 5.4.8 to 5.5.2, the meta formatting codes in groups doesn't seem to work anymore.

### Details
Plugin version: 5.5.2

Software version:  Paper 1.14.4

### Configuration file(s)

configuration file: 
```
enabled: true
remember-toggled-tablist-to-file: true
hide-tab-when-player-vanished: true
disabled-worlds: []
blacklisted-players: []

custom-variables:
  <name>: "&5&o%player%"
  <lines>: "&5&m======================"

interval: 100
random: false

header:
- "<lines>\n&r&e&lYukkuriCraft"
- "&6Ping:&r %ping%&7ms &6TPS:&r %tps%"

footer:
- "&e&l Players:&6 %online-players%&7/&6%max-players%"
- "&b&ndiscord.yukkuricraft.net\n<lines>"

per-world: []
per-player: []
per-group: []
```

Groups
```
# Global group to display for all players
# Leave it empty or remove it, if you don't want to use
globalGroup:
  prefix: ''
  suffix: ''
groups:
  elder:
    prefix: '&e '
  advisor:
    prefix: '&1 '
  legendary:
    prefix: '&b '
  role_tempyoukai:
    prefix: '&a '
  builder:
    prefix: '&d '
  retired:
    prefix: '&2 '
  sysadmin:
    prefix: '&3 '
  owner:
    prefix: '&b '
  senior:
    prefix: '&6 '
  lead_builder:
    prefix: '&5 '
  mediator:
    prefix: '&9 '
  adult:
    prefix: '&7 '
  child:
    prefix: ' '
    suffix: ''
  admin:
    prefix: '&4 '
  mixin_headgrabber: {}
  mixin_notify_bad_behavior: {}
  role_building_contestant: {}
  mixin_protectedbuildable_user: {}
  mixin_openinv: {}
  role_legendarytempyoukai: {}
  probation: {}
  infant: {}
  mixin_protected_builder: {}
  lead_staff: {}
  mixin_time_weather: {}
  mixin_voxel: {}
  mixin_protected_user: {}
  mixin_griefdefender_defaults: {}
  staff: {}
  mixin_navigate: {}
  mixin_ban_kick: {}
  mixin_coreprotect: {}
  mixin_tp: {}
  mixin_spawn_eggs: {}
  mixin_worldedit: {}
  mixin_protectedbuildable_trusted: {}
  mixin_powertool: {}
  mixin_vanish: {}
  griefdefender_definition: {}
  griefdefender_option: {}
  griefdefender_override: {}
  griefdefender_default: {}
  griefdefender_claim: {}
  staff_alt: {}
  mixin_global_mobgrief: {}
  mixin_protected_trusted: {}
  mixin_enable_spawn_eggs: {}
  mixin_mixin_disable_spawn_eggs: {}
  mixin_disable_spawn_eggs: {}
```

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/11007080/109794152-7b4d1380-7c0d-11eb-894a-979a14d06f7b.png)
