### ISSUE TITLE
Essentials nickname isn't hex colored in TabList

### ISSUE THREAD

**Issue by Kanin** [montlikadani/TabList#254]
### Type of bug

Compatibility issue

### TabList version

[01:07:41 INFO]: TabList version 5.5.5
[01:07:41 INFO]: An ultimate animated tablist.
[01:07:41 INFO]: Author: montlikadani

### Software version

This server is running Purpur version git-Purpur-1308 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4afd4e on ver/1.17.1)

### Relevant plugins

[01:09:12 INFO]: Plugins (23): BetterSleeping4, BuycraftX, DeluxeChat, DeluxeChatHex, DeluxeTags*, DiscordSRV, EpicRename, Essentials, FastAsyncWorldEdit (WorldEdit), GSit, JustOneMore*, LuckPerms, Maintenance, mcMMO, Orebfuscator, PlaceholderAPI, PlayTime*, ProtocolLib, RightClickHarvest, ServerListPlus, TabList, Towny, TownyChat

### TabList configuration files

https://paste.gg/p/anonymous/f7100b24a0f3448b81db0a0849c5cbd0

### Bug description

Nicknames with hex codes in them via Essentials do not appear colored in the tablist.

![image](https://kanin.boob.bot/2021/08/02/vWu2)
![image](https://kanin.cannot.date/2021/08/02/2b0R)

**Comment by montlikadani** [comment]
Please install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.

**Comment by Kanin** [comment]
> Please install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.

![image](https://kanin.naila.bot/2021/08/03/1AZ1)

**Comment by Kanin** [comment]
Any updates?

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/f0bd61d3b3cdfd448c321736125fd75f10392d4b

This commit will fixes this issue, install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, you can close this issue if resolved.

**Comment by Kanin** [comment]
> [f0bd61d](https://github.com/montlikadani/TabList/commit/f0bd61d3b3cdfd448c321736125fd75f10392d4b)
> 
> This commit will fixes this issue, install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, you can close this issue if resolved.

Still having the issue, exact same result as the screenshot above.

**Comment by montlikadani** [comment]
> Still having the issue, exact same result as the screenshot above.

I can't reproduce

![image](https://user-images.githubusercontent.com/30026208/128682979-aecfcb0c-e072-4e7e-9703-7b647b429346.png)

**Comment by Kanin** [comment]
> > Still having the issue, exact same result as the screenshot above.
> 
> I can't reproduce
> 
> ![image](https://user-images.githubusercontent.com/30026208/128682979-aecfcb0c-e072-4e7e-9703-7b647b429346.png)
> 
> You probably installed the wrong file.

Okay it appears to be an issue with the hex code being prefixed by & (&#FA66077) as that's what's in the documentation for using hex codes. Any chance this could be fixed? For what it's worth it does work in tablist when removing the &, but it does not in chat.

**Comment by montlikadani** [comment]
> Okay it appears to be an issue with the hex code being prefixed by & (&#FA66077) as that's what's in the documentation for using hex codes.

Where in the documentation?

**Comment by Kanin** [comment]
> > Okay it appears to be an issue with the hex code being prefixed by & (&#FA66077) as that's what's in the documentation for using hex codes.
> 
> Where in the documentation?

https://essentialsx.net/wiki/Color-Permissions.html `rgb | &#RRGGBB`

**Comment by montlikadani** [comment]
Well, I used essentials's nickname too, I gave this text with the starting hex color `&#FA6607Name` ![](https://via.placeholder.com/15/FA6607/000000?text=+) and worked.

**Comment by Kanin** [comment]
![image](https://kanin.ourmainfra.me/2021/08/10/XLtv)
![image](https://kanin.ourmainfra.me/2021/08/10/D56W)

**Comment by Kanin** [comment]
It seems to be ignoring #FA660 and just reading &7

**Comment by Kanin** [comment]
Also, any idea why it takes quite a while to add peoples luckperms prefix to their name in tab after they join? A few minutes it seems.

**Comment by montlikadani** [comment]
It depends from the `refresh-interval` in config

**Comment by montlikadani** [comment]
Can you show your groups file from TabList?

**Comment by Kanin** [comment]
> It depends from the `refresh-interval` in config

It actually appears some members join and instantly get a group, while others take a while. ![image](https://kanin.boob.bot/2021/08/10/nbJf) as you can see here JCoDog joined after Mayurr and got the prefix, but Mayurr did not. Yeah of course one moment.

**Comment by Kanin** [comment]
```yml
# Format of the displayed name: prefix - tabname - suffix
# This will be applied to all players without any other group assigned
globalGroup:
  prefix: "%luckperms_prefix%&r "
  tabname: "%essentials_nickname%"
  suffix: ""

groups:
  # Vault group name OR player name OR custom group name (custom is assigned via permission)
  # exampleGroup:
  #   prefix: "&a[&cStaff&a]&6 "
  #   tabname: "%player-displayname%"
  #   suffix: ""
  #   permission: tablist.staff
  admin:
    prefix: "%luckperms_prefix%&r "
    tabname: "%essentials_nickname%"
    suffix: ""
    permission: tablist.admin
    sort-priority: 4
  mod:
    prefix: "%luckperms_prefix%&r "
    tabname: "%essentials_nickname%"
    suffix: ""
    permission: tablist.mod
    sort-priority: 3
  builder:
    prefix: "%luckperms_prefix%&r "
    tabname: "%essentials_nickname%"
    suffix: ""
    permission: tablist.builder
    sort-priority: 2
  default:
    prefix: "%luckperms_prefix%&r "
    tabname: "%essentials_nickname%"
    suffix: ""
    permission: tablist.default
    sort-priority: 1

```
