### ISSUE TITLE
Sorting Tablist

### ISSUE THREAD

**Issue by charlie-works** [montlikadani/TabList#260]
### Description

This most likely is already part of the plugin, it's just I can't get it to work. If it already is part of the plugin, can you explain how to turn it on?

**Comment by TheNety** [comment]
If you haven't already created groups in groups.yml, then create them - [https://github.com/montlikadani/TabList/wiki/How-to-create-a-group](url) and then just add sort-priority to each group like in the example below:

```
groups:
  owner:
    prefix: '[Owner]'
    tabname: ''
    suffix: ''
    sort-priority: 99
  builder:
    prefix: '[Builder]'
    tabname: ''
    suffix: ''
    sort-priority: 98
```
