### ISSUE TITLE
is there any way to set groups per world?

### ISSUE THREAD

**Issue by ventoryprod** [montlikadani/TabList#295]
Hi,
I wanted to change the prefix (color) of the player when he enters another world, and so that everyone could see it, but I didn't understand how to do it. Is it possible to do it at all, and if so, how?

**Comment by montlikadani** [comment]
The only way that come into my mind is to create a different group with a specified permission and giving this permission to the player whose world has been changed.

**Comment by TheNety** [comment]
In LuckPerms possible with context https://luckperms.net/wiki/Context

**Comment by ventoryprod** [comment]
I tried to do it, but it seems to me that I'm stupid enough and I don't understand how to do it.

**Comment by TheNety** [comment]
Hello again.
In TabList's groups.yml file create multiple groups like this, in each one change what you want (prefix, suffix) and the permission, which will define what world this will be displayed in. We'll create it for group `Developer` in this example.
```yml
groups:
  developer-world:
    prefix: '&aDEVELOPER '
    tabname: ''
    suffix: ''
    permission: tablist.g.developer-world
  developer-nether:
    prefix: '&cDEVELOPER '
    tabname: ''
    suffix: ''
    permission: tablist.g.developer-nether
  developer-end:
    prefix: '&dDEVELOPER '
    tabname: ''
    suffix: ''
    permission: tablist.g.developer-end
```

Then in LuckPerms `Developer` group add those permissions like this, with the context of whatever world name you want.
![image](https://user-images.githubusercontent.com/42073765/144665265-172bf7a5-cbef-4310-882f-a0515bdabcf6.png)

In case the player in this group is opped, just add this with value false
![image](https://user-images.githubusercontent.com/42073765/144665318-a06da786-c1e3-4b77-87bb-468a02593ff1.png)

Now the prefix for players in Developer group will change depending on what world they're in. Good luck!
