### ISSUE TITLE
Sort by group not working properly

### ISSUE THREAD

**Issue by Rivangek** [montlikadani/TabList#329]
### Type of bug

Other

### TabList version

5.6.1

### Software version

Paper 1.18.1 (git-paper-197)

### TabList configuration files

https://paste.gg/p/anonymous/cc83e54994df4b338328686afea368c1

### Bug description

Basically, you can sort players in tablist by group priority(in the groups.yml) but if I rejoin, my group it's on the bottom instead of the top(even if it does have more priority) BUT my friend still does see his(and others) name under my name.

The only one solution that I have found is reloading the plugin everytime I join.

```yml
groups:
  default:
    prefix: '&7'
  lower_priority:
    prefix: '&4'
  higher_priority:
    prefix: '&b' # I have this group(e.g.) and when I rejoin, I'm still under the "lower_priority" users.
```
