### ISSUE TITLE
Unable to use nicknames with multiple hex codes

### ISSUE THREAD

**Issue by rauenzi** [montlikadani/TabList#364]
### Type of bug

Other

### TabList version
```
  [Wed 23:54:49 INFO ] TabList version 5.6.4
  [Wed 23:54:49 INFO ] An ultimate animated tablist
  [Wed 23:54:49 INFO ] Author: montlikadani
```

### Software version
```
  [Wed 23:55:03 INFO ] Checking version, please wait...
  [Wed 23:55:03 INFO ] This server is running Paper version git-Paper-206 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b9cf1ac)
  You are 1 version(s) behind
  Download the new version at: https://papermc.io/downloads
  Previous version: git-Paper-200 (MC: 1.19.2)
```

### Relevant plugins

EssentialsX@2.19.7
EssentialsXChat@2.19.7

### TabList configuration files

config.yml: https://paste.gg/p/anonymous/f71bbf8e434b4a6889758955bfd25ead

groups.yml:
```yml
globalGroup:
  prefix: ''
  tabname: ''
  suffix: ''

groups:
  # Vault group name OR player name OR custom group name (custom is assigned via permission)
  exampleGroup:
    prefix: '&a[&cStaff&a]&6 '
    tabname: '%player-displayname%'
    suffix: '&7 <12>'
  
  Default:
    prefix: '&f '
    tabname: '%essentials_nickname%'
    suffix: ''
  
  Admin:
    prefix: " &c[Admin] "
    tabname: '%essentials_nickname%'
    suffix: ""
```

### Bug description

When using multiple hex values in a single nickname (e.g. to create a gradient effect), essentials correctly colors the nickname, however in the TabList, only the first hex color code gets interpreted properly, the rest are treated as just part of the name.

How essentials displays it:
![image](https://user-images.githubusercontent.com/6865942/195469944-137d596d-7e54-4a37-a462-21514015f376.png)

In the TabList
![image](https://user-images.githubusercontent.com/6865942/195470047-9f6893fa-7b2d-4639-9af7-fc7c8969b192.png)
