### ISSUE TITLE
Prefix's are weird (group.yml)

### ISSUE THREAD

**Issue by rockyhawk64** [montlikadani/TabList#39]
### Describe the bug (required) (spigot 1.12.2)
So I have a couple ranks (with PEX) that I have tested this on (Titan, Co-Owner and Owner). They all have the same prefix except things like different colours and different font types (some are bold). Out of all the ranks the only one that works is Owner out of the three.

### Plugin version (required)
2.9

### Console error (required)

no console error

### Config.yml or other file
Send the config.yml or other file.

**GROUPS.YML**
```
# DO NOT CHANGE THIS!
config-version: 1

# Group prefixes and suffixes. (Requires a permission system.)
# Unlimited group.
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols
groups:
  '1':
    prefix: '&5[&dOwner&5]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.owner
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  '2':
    prefix: '&4[&cCo-Owner&4]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.coowner
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  '3':
    prefix: '&1[&9Admin&1]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.admin
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  '4':
    prefix: '&6[&eMod&6]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.mod
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  '5':
    prefix: '&2[&aHelper&2]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.helper
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  '6':
    prefix: '&8[&7Member&8]&7 '
    suffix: ''
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.member
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  'd1':
    prefix: '&f&l[&7&lHero&f&l]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.hero
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  'd2':
    prefix: '&f&l[Master]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.master
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  'd3':
    prefix: '&6&l[&e&lChampion&6&l]&r '
    suffix: '&7 <12>'
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.champion
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  'd4':
    prefix: '&3&l[&b&lTitan&3&l]&r '
    suffix: ''
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.titan
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
```

**PERMISSIONS.YML** (pex)
```
groups:
  Member:
    default: true
    build: true
    permissions:
    - guishop.use
    - rtp.use
    - essentials.motd
    - essentials.afk
    - essentials.back
    - essentials.back.ondeath
    - essentials.depth
    - essentials.delhome
    - essentials.help
    - essentials.home
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.msg
    - essentials.ping
    - essentials.r
    - essentials.rules
    - essentials.seen
    - essentials.sethome
    - essentials.signs.use.disposal
    - essentials.spawn
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.balance
    - essentials.pay
    - essentials.afk.auto
    - essentials.seen
    - essentials.time
    - essentials.warp
    - essentials.warp.list
    - tablist.member
    options:
      default: 'true'
  Helper:
    default: false
    inheritance:
    - Member
    build: true
    permissions:
    - essentials.tp
    - essentials.sethome.multiple.staff
    - essentials.god
    - essentials.vanish
    - essentials.vanish.see
    - essentials.vanish.interact
    - essentials.fly
    - -tablist.member
    - tablist.helper
  Mod:
    default: false
    inheritance:
    - Helper
    - Member
    build: true
    permissions:
    - essentials.gamemode
    - essentials.give
    - -tablist.member
    - -tablist.helper
    - tablist.mod
  Admin:
    default: false
    inheritance:
    - Helper
    - Member
    - Mod
    build: true
    permissions:
    - essentials.gamemode
    - essentials.give
    - -tablist.member
    - -tablist.helper
    - -tablist.mod
    - tablist.admin
  Co-Owner:
    default: false
    build: true
    permissions:
    - -tablist.member
    - -tablist.helper
    - -tablist.mod
    - -tablist.admin
    - -tablist.owner
    - -tablist.hero
    - -tablist.master
    - -tablist.champion
    - -tablist.titan
    - '*'
  Owner:
    default: false
    build: true
    permissions:
    - -tablist.member
    - -tablist.helper
    - -tablist.mod
    - -tablist.admin
    - -tablist.coowner
    - -tablist.hero
    - -tablist.master
    - -tablist.champion
    - -tablist.titan
    - tablist.owner
    - '*'
  Hero:
    inheritance:
    - Member
    permissions:
    - -tablist.member
    - tablist.hero
  Master:
    inheritance:
    - Member
    - Hero
    permissions:
    - -tablist.member
    - -tablist.hero
    - tablist.master
  Champion:
    inheritance:
    - Member
    - Hero
    - Master
    permissions:
    - -tablist.member
    - -tablist.hero
    - -tablist.master
    - tablist.champion
  Titan:
    inheritance:
    - Member
    - Hero
    - Master
    - Titan
    permissions:
    - -tablist.member
    - -tablist.hero
    - -tablist.master
    - -tablist.champion
    - tablist.titan
schema-version: 1
users:
```
**CONFIG.YML**
```
#=================================OOO====================================#
#                     TabList Configuration File                         #
#=================================OOO====================================#
# config.yml file. Plugin version: 2.9                                   #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configuration]                                                #
# https://github.com/montlikadani/TabList/blob/master/config.yml         #
#                                                                        #
# [Placeholders]                                                         #
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/             #
#                                                                        #
# [Other placeholders]                                                   #
# https://github.com/montlikadani/TabList/wiki/Placeholders              #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - In case of an error, write here:                                     #
# https://github.com/montlikadani/TabList/issues                         #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/TabList/wiki/Symbols                   #
# - If the string is empty does not send the message.                    #
#=================================OOO====================================#

#=========================================#
#                Settings                 #
#=========================================#
# PlaceholderAPI use for the plugin.
placeholderapi: true

# Different playerlist in different world.
per-world-player-list: false

# Remove the NPC name from the tab?
remove-npc-name-from-tab: false

# Fake players that are on the tab.
enable-fake-players: false

# Used for %time% placeholder.
# Formats/examples: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
time-format: 'dd/MM/yyyy'

# Custom variables.
# Unlimited variables.
# Use: <something>: '&6Message...'
custom-variables:
  <name>: '&5&o%player_name%'
  <lines>: '&5&m======================'

# Enables to change prefix & suffix in player tablist.
change-prefix-suffix-in-tablist:
  enable: true
  # Refresh interval. (In ticks!)
  refresh-interval: 200
  # Changing type.
  # Types:
  # scoreboard - Max. character is 16 in prefix & suffix.
  # namer - Max. character unlimited. (WARNING! Overwrites the tabname function.)
  changing-type: scoreboard
  # Player name type that will be changed on the tab.
  # Types:
  # name - Player name.
  # displayname - Player display name.
  player-name-type: name

# Tablist objective type.
tablist-object-type:
  enable: false
  # Types:
  # ping - ping of player
  # health - health of player
  type: ping
  # Objective settings.
  object-settings:
    # The ping side next to the player's name indicates the right side.
    ping:
      # Ping update time interval.
      update-interval: 3
      # Which worlds do not show up in ping (world names)?
      disabled-worlds: []
    # The player health (life) the player's name indicates the right side.
    health:
      # Which worlds show your health in tab?
      disabled-worlds:
      - world_the_end
      # Blacklisted players who do not show the icon beside the player's name in the tab.
      blacklisted-players:
      - exampleplayer
      - players

# Player tab name.
tabname:
  # Allow change player tab name.
  # Warning if this is false, the command will not be registered either. Requires server restart!
  enable: true
  # How many letters should be allowed?
  max-name-length: 200
  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false
  # Enables color coding for tab names. ("&")
  enable-color-code: true
  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: '&6'
  # Which worlds can not change a tab name?
  disabled-worlds: []
  # Which names can not be used?
  # WARNING! Color codes are NOT considered in command.
  blacklist-names:
  - tabname
  # Use %name%, %sender%, %newline%, %prefix% placeholder.
  # >> NO supported the PlaceholderAPI! <<
  other-changed-name-message: '&3Your name is changed to&r %name%&3 by&e %sender%&3.'

# Tablist. Header & footer with animation.
# Use \n, %staff-online%, %ip-address%, %level%, %xp%, %mc-version%, %motd%, %ping%, %servername%, %online+1%,
# %max-players%, %online-players%, %server-time%, %server-ram-free%, %server-ram-max%, %server-ram-used% placeholders.
# Use placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols
tablist:
  # Enable the tab? (Header & footer)
  enable: true
  # What world does not display the tab?
  disabled-worlds:
  - lobby
  - hub
  # Blacklisted players, where the player not see the tab.
  blacklisted-players: []
  # Tab update time interval. (In ticks!)
  # Set 0 to disable the tab refresh.
  interval: 4
  header:
    - '&b&lFortitudeMC\n&7    <75>&c W&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&6&lFortitudeMC\n&7    <75>&c We&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&4&lFortitudeMC\n&7    <75>&c Wel&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&9&lFortitudeMC\n&7    <75>&c Welc&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&a&lFortitudeMC\n&7    <75>&c Welco&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&e&lFortitudeMC\n&7    <75>&c Welcom&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&5&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&b&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&6&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&4&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&9&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&a&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&e&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&5&lFortitudeMC\n&7    <75>&c Welcome&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&b&lFortitudeMC\n&7    <75>&c Welcom&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&6&lFortitudeMC\n&7    <75>&c Welco&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&4&lFortitudeMC\n&7    <75>&c Welc&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&9&lFortitudeMC\n&7    <75>&c Wel&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&a&lFortitudeMC\n&7    <75>&c We&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&e&lFortitudeMC\n&7    <75>&c W&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&5&lFortitudeMC\n&7    <75>&c  &c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&b&lFortitudeMC\n&7    <75>&c &c&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
  footer:
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&l Website&7:&2 &nFortitudeMC.buycraft.net&7 <28>'
  # Per world tablist.
  # Unlimited world.
  per-world:
    enable: false
    world_nether:
      header:
        - '&3This is a per world plugin&6 Tab&aList&3.'
      footer:
        - '&6World:&7 %player_world%'
    world:
      header:
        - '&cThis is a per world plugin&6 TabList'
        - '&6This is a per world plugin&3 TabList'
        - '&3This is a per world plugin&a TabList'
        - '&aThis is a per world plugin&7 TabList'
      footer:
        - '&6World:&7 %player_world%'

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TabList plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline%, %prefix% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v2.9&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: tablist.plugininfo
default-can-see-plugin-information: false

# Unknown-command - If more than one word/letter you write to it.
# Example: /tl reload something...
# Use %command% placeholder.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
# >> NO supported the PlaceholderAPI! <<
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'

# DO NOT CHANGE THIS!
config-version: 4
```

### Screenshots (optional)
![2018-07-20_14 17 50](https://user-images.githubusercontent.com/18727981/42983136-5e755d4e-8c28-11e8-9968-081065de4c68.png)
![2018-07-20_14 18 02](https://user-images.githubusercontent.com/18727981/42983137-5ea6ab6a-8c28-11e8-8359-93c0ba1d033f.png)
![2018-07-20_14 18 16](https://user-images.githubusercontent.com/18727981/42983138-5edbae82-8c28-11e8-8e98-2cbe8e53b660.png)
