### ISSUE TITLE
Permissions checked too frequently?

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#41]
### Describe the bug
Permissions are checked for every permission in groups.yml, for every player online, every 90 seconds. Permissions to do change that frequently (almost never in my case). I would prefer that permissions were checked on permissions changes, or if not trappable, then on **/tablist reload**.
 
### Plugin version
Spigot 1.13 latest
TabList 3.0

### Console error (player name replaced with "playerName")
[16:37:28 INFO]: [LP] VB > playerName - blackdog.faction.black - true
[16:38:58 INFO]: [LP] VB > playerName - blackdog.faction.black - true
[16:40:28 INFO]: [LP] VB > playerName - blackdog.faction.black - true
[16:41:59 INFO]: [LP] VB > playerName - blackdog.faction.black - true
[16:43:29 INFO]: [LP] VB > playerName - blackdog.faction.black - true
[16:44:59 INFO]: [LP] VB > playerName - blackdog.faction.black - true
[16:46:29 INFO]: [LP] VB > playerName - blackdog.faction.black - true
[16:48:00 INFO]: [LP] VB > playerName - blackdog.faction.black - true

### groups.yml (relevant segment)
```
  '2':
    prefix: '&0'
    suffix: '&r'
    # This permission must be in the permission system (e.g. GroupManager).
    permission: blackdog.faction.black
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: false
```

**Comment by montlikadani** [comment]
Unfortunately this was expected. There is not much to do, just one.
It is a mistake to write the permission check elsewhere:
- If a player joins and only has permission, then whoever is available on the server and had an update, the player will not update the group.
- If I write the check on `/tl rl` command, then the same error will appear. ^

One solution is that if the player does not have permission, will return (ie will not run longer). But that does not help, as it will spam.

**Comment by SlimeDog** [comment]
- If a player joins and only has permission, then whoever is available on the server and had an update, the player will not update the group.

Why not? The same processing that now occurs every 90 seconds could occur when necessary due to the check.

- If I write the check on /tl rl command, then the same error will appear. ^

^^^

**Comment by montlikadani** [comment]
I explain it more intelligently.
So, if the player joins the server and only has the permission in the join event, then the only group that will join the player will be visible.
Yes, I've typed in a scheduler to update the player and group permissions for the time set to show the group to the player.

If there were no such permissions, the entire server would be discarded.

**Comment by SlimeDog** [comment]
I will look for an alternative tablist plugin that does not feel the need to check permissions for every player for every configured group every 90 seconds. In the interim, I have disabled groups, which limits the functionality of TabList. :(

**Comment by montlikadani** [comment]
_**This bug has been fixed in this version:** https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=239769_

**Comment by montlikadani** [comment]
@SlimeDog 
Do you still use this plugin? And does it really work?

**Comment by SlimeDog** [comment]
I do. I'll check when I get home. Thanks.

**Comment by SlimeDog** [comment]
Spigot 1.13
Tablist 3.1

It is now checking the relevant permission every 30 seconds! Do I need to change something in the config.yml?

**Comment by montlikadani** [comment]
Then this not working again.

**Comment by SlimeDog** [comment]
I don't understand. Isn't that how it is supposed to work?

**Comment by montlikadani** [comment]
I mean, that permission does the same thing as spam to the console you first sent a message to. (LuckPerms spam console)

**Comment by SlimeDog** [comment]
Yes, but only every _refresh-interval_ seconds in the tablist, which I have now configured to 300 seconds (5 minutes). That is satisfactory, unless there is some other issue.

**Comment by montlikadani** [comment]
I have a problem that I do not know what code would solve this, that when a player has a group already set and by the specified time (eg 90 seconds) if has reached the specified time, will check the permission to see if has it . I want to solve this.

**This feature, where and how did LuckPerms send the console to a controlled permission or something similar?** This is what I mean: _[16:37:28 INFO]: [LP] VB > playerName - blackdog.faction.black - true_

**Comment by SlimeDog** [comment]
LuckPerms has this feature. It reports permission checks to the console/log, as specified by:
```
luckperms verbose on [optional logic]
```
For example, to report checks for TabList groups per the configuration below, the commands are:
```
luckperms verbose on & tablist.staff
luckperms verbose on & blackdog
```

In TabList/groups.yml:
```
groups:
  '1':
    prefix: ' &c*&r'
    suffix: ''
    # This permission must be in the permission system (e.g. PermissionsEx).
    permission: tablist.staff
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: false
  '2':
    prefix: '&0'
    suffix: '&r'
    # This permission must be in the permission system (e.g. GroupManager).
    permission: blackdog.faction.black
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: false
```
