### ISSUE TITLE
Groups and weighting

### ISSUE THREAD

**Issue by Mercifiyer** [montlikadani/TabList#42]
Hi, the plugins grouping system has little to no weighting aspect. I arrange groups in the order of which i'd like to see them in tab and they just go everywhere without any order what so ever.
![2018-08-05 20_48_19-minecraft 1 13](https://user-images.githubusercontent.com/37215049/43685155-eabf60fe-98f0-11e8-8aea-ea593a16eecf.png)

```
groups:
  '6':
    prefix: '&8'
    suffix: ''
    # This permission must be in the permission system.
    permission: tablist.commoner
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  '5':
    prefix: '&2DONATOR '
    suffix: ''
    # This permission must be in the permission system.
    permission: tablist.donator
    disable-for-ops: true
  '4':
    prefix: '&cSTAFF '
    suffix: '&9 <12>'
    # This permission must be in the permission system.
    permission: tablist.staff
    disable-for-ops: false
  '3':
    prefix: '&9BUILDER '
    suffix: '&9 <12>'
    # This permission must be in the permission system.
    permission: tablist.builder
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: true
  '2':
    prefix: '&4NETWORK MANAGER '
    suffix: '&9 <12>'
    # This permission must be in the permission system.
    permission: tablist.nm
    # If this is true then op players will not display the group prefix and suffix in tablist.
    disable-for-ops: false
  '1':
    prefix: '&4OWNER '
    suffix: '&9 <12>'
    # This permission must be in the permiss
```
