### ISSUE TITLE
cant iniciate in 1.20

### ISSUE THREAD

**Issue by chagohunt** [montlikadani/TabList#420]
### Type of bug

Error in console

### TabList version

TabList version 5.7.2 An alternative tablist plugin to replace vanilla empty tab Author: montlikadani

### Software version

This server is running CraftBukkit version 3770-Spigot-81b9def-68b3205 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT)

### Console error (if applicable)

[11:48:59] [Server thread/INFO]: [TabList] Enabling TabList v5.7.2
[11:48:59] [Server thread/WARN]: [TabList] Loaded class net.kyori.adventure.text.Component from SCore v3.9.85 which is not a depend or softdepend of this plugin.
[11:48:59] [Server thread/ERROR]: Error occurred while enabling TabList v5.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer
	at hu.montlikadani.tablist.utils.Util.applyMinimessageFormat(Util.java:44) ~[?:?]
	at hu.montlikadani.tablist.utils.Util.applyMinimessageFormat(Util.java:36) ~[?:?]
	at hu.montlikadani.tablist.utils.variables.Variables.replaceMiscVariables(Variables.java:122) ~[?:?]
	at hu.montlikadani.tablist.config.constantsLoader.TabConfigValues.objectToArrayConversion(TabConfigValues.java:126) ~[?:?]
	at hu.montlikadani.tablist.config.constantsLoader.TabConfigValues.loadValues(TabConfigValues.java:45) ~[?:?]
	at hu.montlikadani.tablist.config.Configuration.loadFiles(Configuration.java:49) ~[?:?]
	at hu.montlikadani.tablist.TabList.onEnable(TabList.java:93) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 18 more

### TabList configuration files
```
hook:

  # Hook to PlaceholderAPI to use custom placeholders.
  placeholderapi: true

# Fake players that can be added to the player list.
fake-players:
  enabled: false

  # Do we count the added fake players to the %online-players% placeholder?
  count-fake-players-to-online-players: false

# If enabled, the gray color will not appear to other players when the player's game mode is spectator.
# The gray color will only show for the spectator player.
remove-gray-color-from-tab-in-spectator: false

# true - does not count vanished players in %online-players% placeholder.
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
ignore-vanished-players-in-online-players: true

# true - count vanished staff in %staff-online% placeholder,
# but they need to have "tablist.onlinestaff" permission set.
# false - does not count vanished staff in the %staff-online% placeholder
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
count-vanished-staffs: false

# Hide player from player list when a player is AFK?
# Requires Essentials or CMI plugin!
hide-player-from-tab-when-afk: false

# Hide all players from the player list?
# This removes all players from the player list,
# resulting to only display the tablist with header and footer without players.
hide-players-from-tablist: false

# Different player list in different world.
per-world-player-list:
  enabled: false

  # You can specify worlds, which will share the same list of players
  world-groups:

    # The key name, can be anything
    example1:
    - exampleWorld
    - exampleAnotherWorld
    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2

# Placeholders formatting
placeholder-format:

  # When the player changes the AFK status, change his tablist name format?
  afk-status:
    enable: true

    # Should the AFK format display in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    # Show player's group if the player is AFK?
    show-player-group: true

    # Format when the player is AFK.
    format-yes: '&7 [AFK]&r '

    # Format when the player is not AFK.
    format-no: ''

    # Sort AFK players to the bottom of the player list?
    sort-last: false
  time:

    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: GMT0

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Format of %server-time% placeholder.
    time-format: mm:HH

    # Format of %date% placeholder.
    date-format: dd/MM/yyyy

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%ping% <= 200'
    - '&6%ping% >= 200'
    - '&c%ping% > 500'

  # TPS color format for %tps% placeholder.
  tps:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 19.14
    size: 2

# Enable changing of prefix & suffix in player list?
change-prefix-suffix-in-tablist:
  enable: true

  # Refresh interval in server ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0, then you will need to execute the /tl reload command to refresh the groups.
  refresh-interval: 40

  # Disable groups in these worlds.
  disabled-worlds:

    # Use the list as whitelist?
    use-as-whitelist: false
    list:
    - myWorldWithUpper

  # Automatically add groups from another plugins to the tablist groups.yml on every reload?
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: true

  # Hide player's group in player list when the player is vanished?
  # Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
  hide-group-when-player-vanished: false

  # Do you want to assign global group to normal groups?
  # true - "globalGroupPrefix + normalGroupPrefix"
  # false - "normalGroupPrefix"
  assign-global-group-to-normal: false

  # Prefer player's primary Vault group when assigning tablist group from groups.yml?
  # true - player will be assigned their primary vault group where possible
  # false - applies the group that has the higher priority in the permission plugin
  prefer-primary-vault-group: true

  # Follow the name tag visibility for players to show the name tag above player or not,
  # depending if a scoreboard team with visibility 'hidden' is exist.
  # true - Follows the name tag visibility and hides if there is a scoreboard team created with visibility 'hidden'
  # false - Always shows the name tag above player
  followNameTagVisibility: false

# Tablist objective types
# Shows your current health (with life indicator), your current ping or any NUMBER placeholder
# after the player's name (before the ping indicator).
tablist-object-type:

  # Types:
  # none - disables tablist objects
  # ping - player's ping
  # health - player's health
  # custom - custom placeholder
  type: none

  # How often should it refresh the values in seconds?
  refresh-interval: 40

  # In these worlds the objects will not be displayed
  disabled-worlds:
  - testingWorld
  object-settings:
    health:
      restricted-players:
      - exampleplayer
      - players

    # Custom placeholder - accepts only number-ending placeholders, like %level%
    custom:
      value: '%level%'

# Check for updates?
check-update: true

# Download new releases to "releases" folder?
# This only works if the "check-update" is true.
download-updates: false

# Log plugin messages to console?
logconsole: true

# This option monitors server performance. If the server's TPS is less than the set value,
# TabList will cancels all currently running schedulers to improve server performance.
# TabList will not restart these schedulers (ie animations, group updates, etc.),
# so you have to do it manually, by reconnecting to the server or by reloading the plugin.
# At values below 8-5, TabList is almost unable to stop its own running processes,
# as the server is already under a very heavy load.
# The values should be between 5-18
# If the value is below 5 or above 18, the default value will be 16.0
# To disable this feature set to -1
tps-performance-observation-value: -1.0
```

### Bug description

[11:48:59] [Server thread/INFO]: [TabList] Enabling TabList v5.7.2
[11:48:59] [Server thread/WARN]: [TabList] Loaded class net.kyori.adventure.text.Component from SCore v3.9.85 which is not a depend or softdepend of this plugin.
[11:48:59] [Server thread/ERROR]: Error occurred while enabling TabList v5.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer
	at hu.montlikadani.tablist.utils.Util.applyMinimessageFormat(Util.java:44) ~[?:?]
	at hu.montlikadani.tablist.utils.Util.applyMinimessageFormat(Util.java:36) ~[?:?]
	at hu.montlikadani.tablist.utils.variables.Variables.replaceMiscVariables(Variables.java:122) ~[?:?]
	at hu.montlikadani.tablist.config.constantsLoader.TabConfigValues.objectToArrayConversion(TabConfigValues.java:126) ~[?:?]
	at hu.montlikadani.tablist.config.constantsLoader.TabConfigValues.loadValues(TabConfigValues.java:45) ~[?:?]
	at hu.montlikadani.tablist.config.Configuration.loadFiles(Configuration.java:49) ~[?:?]
	at hu.montlikadani.tablist.TabList.onEnable(TabList.java:93) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3770-Spigot-81b9def-68b3205]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 18 more
