### ISSUE TITLE
[Multi Language] 

### ISSUE THREAD

**Issue by f3f5-dev** [montlikadani/TabList#435]
if player set language russia - tab in russia

```
Language:
  # The default language to be used if auto-lang is off or no matching language file was found.
  default-language: en_us
  # Enable / Disable locale based messages.
  auto-language: true
```
![Screenshot_2](https://github.com/montlikadani/TabList/assets/137526883/bed4b0a7-168b-469a-adde-d8f3e5c24dbb)

Used depency to make better system config & lang
```

        <dependency>
            <groupId>com.github.thatsmusic99</groupId>
            <artifactId>ConfigurationMaster-API</artifactId>
            <version>v2.0.0-BETA-7</version>
        </dependency>
```

example plugin: https://github.com/moom0o/AnarchyExploitFixes
