### ISSUE TITLE
suffix not working

### ISSUE THREAD

**Issue by MrFadeFancy** [montlikadani/TabList#471]
### Type of bug

General issue

### TabList version

5.7.3

### Software version

 This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Relevant plugins

https://prnt.sc/AK0NPbLAetUz

### TabList configuration files
```
hook:
  placeholderapi: true

fake-players:
  enabled: false

  count-fake-players-to-online-players: false

remove-gray-color-from-tab-in-spectator: true

ignore-vanished-players-in-online-players: true

count-vanished-staffs: false

hide-player-from-tab-when-afk: false

hide-players-from-tablist: false

per-world-player-list:
  enabled: false

  world-groups:
    example1:
    - exampleWorld
    - exampleAnotherWorld
    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2

placeholder-format:

  afk-status:
    enable: false

    show-in-right-or-left-side: true
    show-player-group: true

    format-yes: '&7 [AFK]&r '

    format-no: ''

    sort-last: false
  time:

    time-zone: GMT0

    use-system-zone: false

    time-format: mm:HH

    date-format: dd/MM/yyyy

  ping:
    enable: false

    formats:
    - ''
  tps:
    enable: false

    formats:
    - ''

    size: 2

change-prefix-suffix-in-tablist:
  enable: true

  refresh-interval: 4

  disabled-worlds:

    use-as-whitelist: false
    list:
    - myWorldWithUpper

  sync-plugins-groups-with-tablist: true

  hide-group-when-player-vanished: false

  assign-global-group-to-normal: false

  prefer-primary-vault-group: false

  use-luckperms-weight-to-order-groups-to-first-place: true

  followNameTagVisibility: false

tablist-object-type:

  type: none

  refresh-interval: 3

  custom-value: '%level%'

  disabled-worlds:
  - testingWorld

check-update: true

download-updates: false

logconsole: true
```

### Bug description

for some reason luckperms suffix isn't working
%luckperms_suffix%

I did /lp user MrFadeFancy meta setsuffix 10 &f&lIRON   
and its not showing up in tablist
