### ISSUE TITLE
Default per-world tablists

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#50]
Spigot 1.13.1 latest
TabList 3.3

At present, if
```
  per-world:
    enable: true
```
then any world not listed will have no header or footer. I would prefer than they use the "default" header and footer -- the one that one be used if
```
  per-world:
    enable: false
```
otherwise, every world has to be listed.

Example:
```
tablist:
  header:
    - 'default header'
  footer:
    - 'default footer'
  # Per world tablist.
  # Unlimited world.
  per-world:
    enable: true
    world_xyzzy:
      header:
        - 'a per-world header'
      footer:
        - 'a per-world footer'
```
So world_xyzzy has the specified header and footer, but other worlds have none. They should display
```
tablist.header
tablist.footer
```
