### ISSUE TITLE
Update tick

### ISSUE THREAD

**Issue by Osybear** [montlikadani/TabList#75]
### Describe the bug (required)
&6Online: &7%online-players%/%max-players%
the %online-players% placeholder is not being updated every 4 ticks!

### Software (Bukkit/Spigot) version (required)
This server is running Paper version git-Paper-513 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Config.yml 
```
  # Tab update time interval. (In ticks!)
  # Set 0 to disable the tab refresh.
  interval: 4
  header:
    - "&6&lBEARCRAFT.ONLINE"
  footer:
    - "&6Online: &7%online-players%/%max-players% &6Ping: %ping%&7ms &6TPS: &7%tps%"
```

### Screenshots (optional)
https://imgur.com/a/OjryIeu
